### ISSUE TITLE
A question about badge

### ISSUE THREAD

**Issue by JasonHezz** [rubensousa/FloatingToolbar#9]
Thanks for your great lib.And I have a question  about how to add badge for menu Item.I have checked your code,MenuLayout only add menu icon.Will you support it next version?

**Comment by rubensousa** [comment]
Hi, I won't add support for this since you can add a custom view already. 
You can do this in 2 ways:
1. Use attribute app:floatingCustomView to inflate a custom view and then get it with floatingToolbar.getCustomView().
2. Inflate a view in your activity/fragment and then pass it to the FloatingToolbar with floatingToolbar.setCustomView(view)
